spring:
  jta:
    enabled: true
  datasource:
    url: jdbc:postgresql://124.61.33.143:5432/rendez
    username: randez
    password: randez5432
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
